apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: argocd
    repoURL: https://github.com/chrismlee42/argocd-applications.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
