apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
    # server: https://kubernetes.default.svc
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42-dev/argocd-config.git
      targetRevision: HEAD
    - chart: argo-cd
      helm:
        releaseName: argocd
        valuesObject:
          configs:
            params:
              redis.compression: none
              server.insecure: true
          global:
            domain: argocd.service.clee.private.morphacy.net
          server:
            ingress:
              annotations:
                ingress.cilium.io/tls-passthrough: enabled
      ref: helm
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 8.1.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
