apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cnpg-system
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/cloudnative-pg-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
