apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: default
  sources:
    - chart: external-secrets
      helm:
        releaseName: external-secrets
        valuesObject: {}
      ref: helm
      repoURL: https://charts.external-secrets.io
      targetRevision: "v0.19.1"
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/external-secrets-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
