apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runner-controller
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: github-actions-runner-controller
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/github-actions-runner-controller-config.git
      targetRevision: HEAD
    - chart: gha-runner-scale-set-controller
      helm:
        releaseName: github-actions-runner-controller
        valuesObject:
          githubConfigSecret: github-config
      ref: helm-controller
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.12.1
    - chart: gha-runner-scale-set
      helm:
        releaseName: gha-runners
        valuesObject:
          githubConfigSecret: github-config
      ref: helm-runner
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.12.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
  ignoreDifferences:
    # - group: '*'
    #   kind: '*'
    #   jqPathExpressions:
    #     - |
    #       def parsePath(pathStr):
    #         (pathStr | split(".")[1:]) as $parts | $parts | map(
    #           if test("^\\w+\\[\\d+\\]$") then
    #             capture("(?<key>\\w+)\\[(?<index>\\d+)\\]") | [.key, (.index | tonumber)]
    #           else
    #             [.]
    #           end
    #         ) | add
    #       ;
    #       . as $root | .metadata?.annotations?["custom.argocd.argoproj.io/ignore-path"] as $path | $root | getpath(parsePath($path))
    - # group: core
      kind: Secret
      name: github-config
      namespace: github-actions-runner-controller
      jsonPointers:
        - /data
