apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-k8s-device-plugin
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: nvidia-k8s-device-plugin
    # server: https://kubernetes.default.svc
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/nvidia-k8s-device-plugin-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
