apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: prometheus-operator
    # server: https://kubernetes.default.svc
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42/prometheus-operator-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
