apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
    # server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: secrets-store-csi-driver
      helm:
        releaseName: secrets-store-csi-driver
        valuesObject: {}
      ref: helm
      repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      targetRevision: "v1.5.3"
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42-dev/secrets-store-csi-driver-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
