apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey-operator
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: valkey-operator
    # server: https://kubernetes.default.svc
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42-dev/valkey-operator-config.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
