apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  sources:
    - path: argocd
      ref: path
      repoURL: https://github.com/chrismlee42-dev/vault-config.git
      targetRevision: HEAD
    - chart: vault
      helm:
        releaseName: vault
        valuesObject:
          global:
            enabled: true
            tlsDisable: true
          injector:
            enabled: true
          server:
            auditStorage:
              enabled: true
            dataStorage:
              enabled: true
            enabled: true
            livenessProbe:
              enabled: true
              initialDelaySeconds: 60
              path: "/v1/sys/health?standbyok=true"
            logLevel: debug
            readinessProbe:
              enabled: true
              path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
            service:
              enabled: true
            serviceAccount:
              create: true
              name: vault
            standalone:
              enabled: true
          ui:
            enabled: true
            externalPort: 80
            # service_type: LoadBalancer
      ref: helm
      repoURL: https://helm.releases.hashicorp.com/
      targetRevision: 0.28.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: '*'
      kind: '*'
      managedFieldsManagers:
        - vault-k8s
